# This piece of code was made by ChatGPT because I don't care enough to learn this

name: Build project

on:
        push:
                branches: [main]
        pull_request:

jobs:
        build:
                runs-on: ubuntu-latest

                steps:
                        - name: 📥 Checkout repository
                          uses: actions/checkout@v4

                        - name: Get Qt framework
                          uses: jurplel/install-qt-action@v4
                          with:
                                  version: 6.9.1

                        - name: ⚙️ Set up dependencies
                          run: |
                                  sudo apt-get update
                                  sudo apt-get install -y cmake ninja-build clang g++
                                  sudo apt-get install -y mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev
                                  sudo apt-get install -y libglew-dev libglfw3-dev libglm-dev

                        - name: Cache build directory
                          uses: actions/cache@v4
                          with:
                                  path: build/
                                  key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp') }}
                                  restore-keys: |
                                          ${{ runner.os }}-build-

                        - name: 🏗️ Configure and build
                          run: |
                                  mkdir -p build
                                  cd build
                                  cmake ..
                                  cmake --build . -j$(nproc)

                        - name: 📦 Upload executable
                          uses: actions/upload-artifact@v4
                          with:
                                  name: libQtQuickOpenGLWidget.a
                                  path: |
                                          build/libQtQuickOpenGLWidget.a
                                  if-no-files-found: error
